# Generated by Django 5.0 on 2023-12-08 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_item_location_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Transection',
            fields=[
                ('order_id', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('receive_phone', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('delivery_number', models.CharField(max_length=20)),
                ('receive_name', models.CharField(max_length=100)),
                ('q_sale', models.DecimalField(decimal_places=4, max_digits=8)),
                ('sale_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('total_sale_amount', models.DecimalField(decimal_places=4, max_digits=8)),
                ('sale_pay_method', models.CharField(choices=[('cash', 'Cash'), ('qrscan', 'QR Scan'), ('credit', 'Credit'), ('check', 'Check')], max_length=20)),
                ('sale_vat_id', models.CharField(max_length=30)),
                ('receive_date', models.DateField()),
                ('q_buy', models.DecimalField(decimal_places=4, max_digits=8)),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('delivery_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('remark', models.CharField(max_length=500)),
                ('buy_vat_id', models.CharField(max_length=30)),
                ('total_buy_amount', models.DecimalField(decimal_places=4, max_digits=8)),
                ('buy_pay_method', models.CharField(choices=[('cash', 'Cash'), ('qrscan', 'QR Scan'), ('credit', 'Credit'), ('check', 'Check')], max_length=20)),
                ('pay_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_name', to='account.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='account.item')),
                ('receive_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_location_name', to='account.location')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_name', to='account.supplier')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_location_name', to='account.location')),
            ],
        ),
    ]
